module WhileLSP
  type range = [Integer, Integer]

  type diagnostic = [
    range,              # Location
    String,             # Code
    String              # Message
  ]

  # 型
  #
  # - `:int` 整数型
  #
  type ty = :int

  # ローカル変数の型を記録するための **型環境**
  #
  type type_env = Hash[String, ty]
end
